export type ApiImage = {
  id: number;
  uploaderId: number;
  uploadedTimestamp: Date;
  size: number;
  width: number;
  height: number;
  views: number;
  downloads: number;
  visibility: number;
  hideUploader: number;
  title: string;
  description: string;
  filename: string;
  storage: {
    bucket: string;
    filename: string;
  };
  autodeleteTimestamp: Date | null;
  application: string;
  favorite: boolean;
  folderId: number;
  explosion: number;
  explosionUserViews: number;
  explosionUserDuration: number;
  explosionGlobalViews: number;
  explosionAction: number;
  nsfw: number;
  shareId: number;
  shareCode: string;
  likeCount: number;
  commentCount: number;
};

export type ApiComment = {
  id: number;
  userId: number;
  referenceType: number;
  referenceId: number;
  content: string;
  createdTimestamp: Date;
  parentId: number | null;
  likeCount: number;
};

export type ApiUser = {
  id: number;
  username: string;
  email: string;
  password: string;
  uploadKey: string;
  permissionGroupId: number;
  badges: number;
  createdTimestamp: Date;
  hideProfile: boolean;
  bugsFoundCount: number;
  inviterId: number;
  subscriptionId: number;
  subscriptionGroupId: number;
  language: string;
  bio: string;
  domainId: number;
  domainSub: string;
  domainPath: string;
  domainRandom: boolean;
  avatar: { bucket: string; filename: string } | null;
  avatarDecoration: string | null;
  discordId: string;
  discordUsername: string;
  discordDiscriminator: string;
  discordGlobalName: string;
  discordFlags: number;
  discordPremiumType: number;
  discordAvatar: string;
  discordBanner: string;
  discordAccessToken: string;
  discordRefreshToken: string;
  discordLastUpdate: Date | null;
  discordStatus: number;
  discordClient: number;
  discordActivities: any;
  discordMember: boolean;
  embedType: number;
  embedColor: string;
  embedColorDivergence: number;
  embedTitle: string;
  embedDescription: string;
  embedAuthorName: string;
  embedAuthorUrl: string;
  embedProviderName: string;
  embedProviderUrl: string;
  defaultHideUploader: boolean;
  defaultVisibility: number;
  defaultAutodeleteAfter: any;
  shareCodeLength: number;
  shareCodeGenerator: number;
  useUploadDirectLink: boolean;
  emailConfirmed: boolean;
  emailConfirmationToken: string;
  secureUploadCheck: boolean;
  randomizeFilenames: boolean;
  shareCodeEmojiMode: boolean;
  shareCodeInvisible: boolean;
  shareLinkDiscordExploit: boolean;
  shareLinkDiscordExploitValue: string;
  shareLinkHyperlink: boolean;
  shareLinkHyperlinkValue: string;
  shareLinkCustom: boolean;
  shareLinkCustomValue: string;
  standing: number;
  theme: number;
  primaryColor: number;
  loginStreak: number;
  lastLoginStreakIncreaseTimestamp: Date;
  totalSubscriptionDays: number;
  completedOnboarding: boolean;
  coins: number;
  status: number;
  level: number;
  xp: number;
  claimedLevel: number;
  mouseTrail: number;
  mouseEffect: number;
  welcomeActivities: number;
  customCursor: number;
};

export type ApiLike = {
  id: number;
  userId: number;
  referenceType: number;
  referenceId: number;
  createdTimestamp: Date;
};

export type ApiDomain = {
  id: number;
  name: string;
  ownerId: number;
  addedTimestamp: Date;
  status: number;
  availability: number;
  supportsSubdomain: boolean;
  supportsPath: boolean;
  cloudflareZoneId: string;
  official: boolean;
  lastPingTimestamp: Date;
  failedSinceTimestamp: Date | null;
  uses: number;
};
